<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows10.0.17763.0</TargetFramework>
		<UseWinUI>true</UseWinUI>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<WindowsPackageType>None</WindowsPackageType>
		<ApplicationManifest>App.manifest</ApplicationManifest>
		<TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
	</PropertyGroup>
	<ItemGroup>
	  <None Remove="ControllerView.xaml" />
	</ItemGroup>
	<ItemGroup>
	  <Page Remove="UI\Views\GamecubeController.xaml" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="LibUsbDotNet" Version="2.2.29" />
		<PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.28000.1839" />
		<PackageReference Include="Microsoft.WindowsAppSDK" Version="2.1.3" />
		<PackageReference Include="Nefarius.Utilities.DeviceManagement" Version="5.2.0" />
		<PackageReference Include="Nefarius.ViGEm.Client" Version="1.21.256" />
	</ItemGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.WindowsDesktop.App.WindowsForms" />
		<FrameworkReference Include="Microsoft.WindowsDesktop.App" />
	</ItemGroup>

	<ItemGroup>
	  <None Update="UI\Views\GamecubeController.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </None>
	</ItemGroup>

	<ItemGroup>
	  <Page Update="ControllerView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>
</Project>